In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("./diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
df.describe(include="all")

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [4]:
# converting the data into inputs and outputs

x = df.iloc[:, :-1] # input data
y = df.iloc[:, -1] # output data

x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [5]:
# splitting the data into training data and testing data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
757            0      123             72              0        0  36.3   
765            5      121             72             23      112  26.2   
470            1      144             82             40        0  41.3   
11            10      168             74              0        0  38.0   
725            4      112             78             40        0  39.4   
..           ...      ...            ...            ...      ...   ...   
236            7      181             84             21      192  35.9   
752            3      108             62             24        0  26.0   
277            0      104             64             23      116  27.8   
205            5      111             72             28        0  23.9   
87             2      100             68             25       71  38.5   

     DiabetesPedigreeFunction  Age  
757                     0.258   52  
765                     0.245   30  
470                     0.607   28  
11                      0.537   34  
725                     0.236   38  
..                        ...  ...  
236                     0.586   51  
752                     0.223   25  
277                     0.454   23  
205                     0.407   27  
87                      0.324   26  

[614 rows x 8 columns]

In [6]:
# normalization of the data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x_train)

x_train = scaler.transform(x_train)

x_test = scaler.transform(x_test)

x_train

array([[-1.12327062,  0.04345121,  0.13140979, ...,  0.53415494,
        -0.6241988 ,  1.55711676],
       [ 0.33979294, -0.0186653 ,  0.13140979, ..., -0.73398504,
        -0.66253374, -0.28728285],
       [-0.83065791,  0.69567457,  0.64467702, ...,  1.16194701,
         0.4049471 , -0.45495555],
       ...,
       [-1.12327062, -0.54665564, -0.279204  , ..., -0.53309158,
        -0.04622574, -0.87413728],
       [ 0.33979294, -0.32924785,  0.13140979, ..., -1.02276939,
        -0.18482132, -0.53879189],
       [-0.5380452 , -0.67088866, -0.07389711, ...,  0.81038345,
        -0.42957522, -0.62262824]])

In [7]:
# running the naive bayes model on the data

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x_train, y_train)

y_prediction = model.predict(x_test)

y_prediction

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [8]:
# evaluating the accuracy of the model

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

score = accuracy_score(y_test, y_prediction)

score * 100

75.97402597402598

In [9]:
# printing the confusion matrix for the model

from sklearn.metrics import confusion_matrix

result = confusion_matrix(y_test, y_prediction)

result

array([[84,  8],
       [29, 33]])